FROM ubuntu:18.04

# Welcome to this DockerFile for the Floorplan To Blender3d project
# All steps of the installation are described below

LABEL MAINTAINER=grebtsew UPDATED=28-06-2020

# Create program install folder
ENV PROGAM_PATH /home/floorplan_to_blender
RUN mkdir -p ${PROGAM_PATH}

# Add our program
ADD ./ ${PROGAM_PATH}/

# Install needed programs
RUN apt-get update && \
	  apt-get install -y \
		curl \
		bzip2 \
		libfreetype6 \
		libgl1-mesa-dev \
		libglu1-mesa \
		libxi6 \
    libsm6 \
		libxrender1 \
    git \
    nano \
    python3-pip \
    python3-dev  && \
	apt-get -y autoremove && \
	rm -rf /var/lib/apt/lists/*

# Install blender

ENV BLENDER_PATH /usr/local/blender/blender
ENV BLENDER_MAJOR 2.79
ENV BLENDER_VERSION 2.79
ENV BLENDER_BZ2_URL https://mirror.clarkson.edu/blender/release/Blender$BLENDER_MAJOR/blender-$BLENDER_VERSION-linux-glibc219-x86_64.tar.bz2

RUN mkdir /usr/local/blender && \
	curl -SL "$BLENDER_BZ2_URL" -o blender.tar.bz2 && \
	tar -jxvf blender.tar.bz2 -C /usr/local/blender --strip-components=1 && \
	rm blender.tar.bz2

RUN pip3 install --upgrade setuptools
RUN pip3 install -r ${PROGAM_PATH}/requirements.txt

# Volume to get data after
VOLUME /media
VOLUME ${PROGAM_PATH}

#CMD [ "python3", "/create_blender_project_from_floorplan.py" ]
WORKDIR ${PROGAM_PATH}
